---
title: "piecewise"
author: "Oliver Causey"
date: "9/14/2020"
output: pdf_document
---



```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning  = FALSE)
devtools::load_all("../BPI/")
library(data.table)
library(corrplot)
library(ggplot2)
library(EnvStats)
library(MASS) #for boxcox
#plot predictors vs residuals. worry if there is a pattern
library(kableExtra)
library(MLmetrics)
library(splines) #for piecewise functions
library(segmented)

library(mgcv)
set.seed(123)
```


```{r functions}
#' Remove commas in numeric column
#' @title rm_comma
#' @param x a character or a character vector
#' @example rm_comma("92,006")
rm_comma <- function(x){
  x <- as.numeric(gsub(",","", x))
  return(x)
}

################
################
################
#function to generate piecewise linear model results
#using the growing window technique.
get_linear_results <- function(window_size) {
  linear_results <- c()
for ( i in 1:(nrow(model_data)-1)) {
  dataset_temp <- as.data.frame(model_data[1:(i + window_size -1),])
  data <- as.data.frame(copy(dataset_temp))
  linear_temp <- lm(acres_corn_US ~ bs(total_order), data = data)

linear_results[i] <- predict(linear_temp, 
                             model_data[i+window_size,1])
                           
}
#get predictions, response
predictions <- unlist(linear_results)[1:(nrow(model_data)-window_size)]
response<- model_data$acres_corn_US[(window_size+1):nrow(model_data)]


#calculate basic metrics and put into tabular form
mae  <- MAE(predictions, response)/1000000
mape <- MAPE(predictions, response)*100
rmse <- RMSE(predictions, response)/1000000

stats_table <- rbind(mae,mape,rmse)
row.names(stats_table) <- c("MAE (Million Acres)", 
                            "MAPE (%) ", 
                            "RMSE (Million Acres)")
stats_table
}


################
################
################
#function to generate linear model results
#using the moving window technique.

moving_window <- function(window_size) {
  linear_results <- c()
for ( i in 1:(nrow(model_data)-1)) {
  dataset_temp <- as.data.frame(model_data[1:(i + window_size -1),])
  data <- as.data.frame(copy(dataset_temp))
  linear_temp <- lm(acres_corn_US ~ ., data = data)

#extract model parameters
#intercept <- coef(summary(linear_temp))["(Intercept)",1]
#slope <- coef(summary(linear_temp))["total_order",1]

#predict next year's acres (i+window_size)
#linear_results[i] <- intercept + slope*model_data[i+window_size,1]
linear_results[i] <- predict(linear_temp, 
                            model_data[i+window_size,1:2])
}


#get predictions and response
predictions <- unlist(linear_results)[1:(nrow(model_data)-window_size)]
response<- model_data$acres_corn_US[(window_size+1):nrow(model_data)]

#calculate basic metrics and put into tabular form
mae  <- MAE(predictions,  response)/1000000
mape <- MAPE(predictions, response)*100
rmse <- RMSE(predictions, response)/1000000

stats_table <- rbind(mae,mape,rmse)
row.names(stats_table) <- c("MAE (Million Acres)", 
                            "MAPE (%) ", 
                            "RMSE (Million Acres)")
stats_table
}


#################
#################
#################
#function to add noise for noise testing
moving_window_jitter <- function(window_size, noise) {
  linear_results <- c()
for ( i in 1:(nrow(model_data)-1)) {
  dataset_temp <- as.data.frame(model_data[1:(i + window_size -1),])
  data <- as.data.frame(copy(dataset_temp))
  linear_temp <- lm(jitter(acres_corn_US, noise) ~ ., data = data)

#extract model parameters
#intercept <- coef(summary(linear_temp))["(Intercept)",1]
#slope <- coef(summary(linear_temp))["total_order",1]

#predict next year's acres (i+window)
#linear_results[i] <- intercept + slope*model_data[i+window_size,1]
linear_results[i] <- predict(linear_temp, 
                           model_data[i+window_size,1:2])
}

#get predications and response
predictions <- unlist(linear_results)[1:(nrow(model_data)-window_size)]
response<- model_data$acres_corn_US[(window_size+1):nrow(model_data)]

#calculate basic metrics
mae  <- MAE(predictions,  response)/1000000
mape <- MAPE(predictions, response)*100 

#put basic metrics into tabular format
stats_table <- rbind(mae,mape,rmse)
row.names(stats_table) <- c("MAE (Million Acres)", 
                            "MAPE (%) ", 
                            "RMSE (Million Acres)")
stats_table
}
```


```{r get_munge_data, echo=FALSE}
munge_data <- function(predictor =1, num_months = 1 ){
feature_data <- readxl::read_xlsx("../data/raw/sales_2006-2020.xlsx")
names(feature_data) <- feature_data[2,]

response_data <- as.data.table(read.csv("../data/raw/acreplanted_national_corn_nass_1926-2020.csv"))


#response data needs an easy to read name
response_data$acres_corn_US <- response_data$CORN...ACRES.PLANTED......b.VALUE..b.

#remove commas from acre data
response_data[, acres_corn_US:=rm_comma(acres_corn_US)]

#feature names are in second row of data
names(feature_data) <- feature_data[2,]

#remove non-data (empty rows and column name are the first two rows of data)
feature_data <- feature_data[3:nrow(feature_data),]


feature_dt <- as.data.table(feature_data)
response_dt <- as.data.table(response_data)


# remove "M" from year and month in sales data. 
feature_dt$year <- gsub( "M", "", as.character(feature_dt$`Market Year`) )
feature_dt$month <- gsub( "M", "", as.character(feature_dt$`MY Month Nbr`))





#assign the same data type to merging column
response_dt$year <- as.integer(response_dt$Year)
feature_dt$year <- as.integer(feature_dt$year)


#merge data
data_by_month <- merge(feature_dt,response_dt,by ="year")

#grab useful columns
columns_to_keep <- c("year",
                     "month",
                     "Dealer Account CY Brand Family",
                     "Order Quantity",
                     "acres_corn_US")


dataset <- data_by_month[, ..columns_to_keep]



dataset$month <- as.numeric(dataset$month)

#grab only data from November and earlier
before_november <- dataset[dataset$month < (num_months + 1),]
national_sales_before_november <- before_november[`Dealer Account CY Brand Family` == "NATIONAL",]
#merge the regional and national brand data

before_november$`Order Quantity` <- as.numeric(before_november$`Order Quantity`)
summed_national_sales <-before_november[, "total_order" :=sum(as.numeric(`Order Quantity`)),
                                               by=.(year,acres_corn_US) ]


cols_to_keep <- c("total_order",  "acres_corn_US", "year")
orders_acres <- unique(summed_national_sales[,..cols_to_keep])

#merge usda projections with features 

#get USDA projection data
USDA <- read.csv("../data/raw/USDACornPlantingProjections.csv")
USDA$year <- as.numeric(substr(USDA$Year2, start = 6, stop = 10)) #Keeping the planting year of the 2 year range

#order by year so that we can use the each row containing the
# first instance of the year variable
USDA_ordered <- setorder(USDA, YearProjected2, year)

#get only the first year predicitons
ordered_projections <- USDA_ordered[match(unique(USDA_ordered$YearProjected2), USDA_ordered$YearProjected2),]

ordered_projections$projection <- as.numeric(ordered_projections$Value*1000000)
ordered_projections$year <- as.numeric(ordered_projections$year)

data_for_model <- merge(orders_acres, ordered_projections, by = "year")

if(predictor == 1 ){
columns_to_keep <- c("total_order",
                     "acres_corn_US")
}else{ columns_to_keep <- c("total_order",
                            "projection",
                            "acres_corn_US")}

model_data <- data_for_model[ ,..columns_to_keep]
model_data <- na.omit(model_data)
model_data$projection
return(model_data)
}



```






```{r sep}


get_piecewise_two_predictors <- function(data) {

gam_results <- c()
for ( i in 1:(nrow(model_data)-8)) {
  dataset_temp <- as.data.frame(model_data[i:(i+8),])
  data <- as.data.frame(copy(dataset_temp))
  
  
  gam_temp <- mgcv::gam(acres_corn_US  ~ s(total_order,projection, k = 8, sp = -1), 
                                      data = data,
                                      method = "REML") 


  gam_results[i] <- predict(gam_temp, 
                           subset(model_data[i+1], 
                                  select = -acres_corn_US))

#  plot(gam_temp, residuals = TRUE, pch = 1)
}
#get predictions, response
predictions <<- unlist(gam_results)[1:6]
response<<- model_data$acres_corn_US[2:7]



#calculate basic metrics and put into tabular form
mae  <- MAE(predictions, response)/1000000
mape <- MAPE(predictions, response)*100
rmse <- RMSE(predictions, response)/1000000

stats_table <- rbind(mae,mape,rmse)
row.names(stats_table) <- c("MAE (Million Acres)", 
                            "MAPE (%) ", 
                            "RMSE (Million Acres)")


kable(stats_table, 
             col.names = c("acres ~ gam(s(projection, sales))"), digits = 2)
}
model_data <- munge_data(predictor =  2, num_months = 1)
get_piecewise_two_predictors(model_data)
```

```{r sep_oct}


get_piecewise_two_predictors <- function(data) {

gam_results <- c()
for ( i in 1:(nrow(model_data)-8)) {
  dataset_temp <- as.data.frame(model_data[i:(i+8),])
  data <- as.data.frame(copy(dataset_temp))
  
  
  gam_temp <- mgcv::gam(acres_corn_US  ~ s(total_order,projection, k = 8, sp = -1), 
                                      data = data,
                                      method = "REML") 


  gam_results[i] <- predict(gam_temp, 
                           subset(model_data[i+1], 
                                  select = -acres_corn_US))

#  plot(gam_temp, residuals = TRUE, pch = 1)
}
#get predictions, response
predictions <<- unlist(gam_results)[1:6]
response<<- model_data$acres_corn_US[2:7]



#calculate basic metrics and put into tabular form
mae  <- MAE(predictions, response)/1000000
mape <- MAPE(predictions, response)*100
rmse <- RMSE(predictions, response)/1000000

stats_table <- rbind(mae,mape,rmse)
row.names(stats_table) <- c("MAE (Million Acres)", 
                            "MAPE (%) ", 
                            "RMSE (Million Acres)")


kable(stats_table, 
             col.names = c("acres ~ gam(s(projection, sales))"), digits = 2)
}
model_data <- munge_data(2, num_months = 2)
get_piecewise_two_predictors(model_data)
```
```{r plot_data_REML.Cp}

model <- mgcv::gam(acres_corn_US ~ s(total_order, 
                                     projection, 
                                     k=8),
                   data = model_data, method = "REML")
plot(model)
```
/newline
```{r plot_results_REML}

fit <- lm(response~predictions)
plot(predictions,response,
     xlab = "s(orders, USDA projections)",
     ylab = "acres_planted")
lines(predictions, fitted(fit), col="blue")

```
```{r describe_data_REML}

model <- mgcv::gam(acres_corn_US ~ s(total_order, 
                                     projection, 
                                     k=8),
                   data = model_data, method = "REML")
model
```
```{r summary_model_REML}
summary(model)

```
```{r sep_oct_gcv}


get_piecewise_two_predictors <- function(data) {

gam_results <- c()
for ( i in 1:(nrow(model_data)-8)) {
  dataset_temp <- as.data.frame(model_data[i:(i+8),])
  data <- as.data.frame(copy(dataset_temp))
  
  
  gam_temp <- mgcv::gam(acres_corn_US  ~ s(total_order,projection, k = 8, sp = -1), 
                                      data = data,
                                      method = "GCV.Cp") 


  gam_results[i] <- predict(gam_temp, 
                           subset(model_data[i+1], 
                                  select = -acres_corn_US))

#  plot(gam_temp, residuals = TRUE, pch = 1)
}
#get predictions, response
predictions <<- unlist(gam_results)[1:6]
response<<- model_data$acres_corn_US[2:7]



#calculate basic metrics and put into tabular form
mae  <- MAE(predictions, response)/1000000
mape <- MAPE(predictions, response)*100
rmse <- RMSE(predictions, response)/1000000

stats_table <- rbind(mae,mape,rmse)
row.names(stats_table) <- c("MAE (Million Acres)", 
                            "MAPE (%) ", 
                            "RMSE (Million Acres)")


kable(stats_table, 
             col.names = c("acres ~ gam(s(projection, sales),
                           \n  k=8, method = GCV.Cp)"), digits = 2)
}
model_data <- munge_data(2, num_months = 2)
get_piecewise_two_predictors(model_data)
```




```{r describe_data_GCV.Cp}

model <- mgcv::gam(acres_corn_US ~ s(total_order, 
                                     projection, 
                                     k=8),
                   data = model_data, method = "GCV.Cp")
model
```
```{r summary_model_GCV}
summary(model)

```



```{r plot_results_GCV}

fit <- lm(response~predictions)
plot(predictions,response,
     xlab = "s(orders, USDA projections)",
     ylab = "acres_planted")
lines(predictions, fitted(fit), col="blue")

```
