---
title: "Regression Analysis"
author: "Song Yuanhong"
date: \today

output:
  html_document:
    toc: true
    toc_float: true
  
header-includes: 
- \usepackage{setspace}\onehalfspacing

fontsize: 11pt
geometry: left=2cm,right=2cm,top=2cm,bottom=2cm
---

```{r setup, echo = F, include=FALSE, message=F, warning=F}
devtools::load_all("../BPI/")
pkg <- c("data.table", "dplyr", "ggplot2", "kableExtra", "tseries", "forecast", "readxl", "glmnet", "getUSDA", "ranger", "scales")
lapply(pkg, library, character.only = T)
```

[USDA QuickStats](https://quickstats.nass.usda.gov/api)

```{r}
main <- fread("pooled_usda.csv")
```

```{r cost, echo=F, warning=F, message=F}
rev_75 <- read_excel("../data/raw/us_corn_cost_return_1975-1995.xls")
rev_75 <- rev_75[c(2, 44, 55, 59, 60), 1:22]
rev_75 <- transpose(rev_75)
names(rev_75) <- c("year", "gross_prod_yera", "cost_corn", "price_corn", "yield_corn")
rev_75 <- rev_75[-1, ]

rev_96 <- read_excel("../data/raw/us_corn_cost_return_1996-2019.xlsx")
rev_96 <- rev_96[c(6, 14, 60, 66, 64), 1:25]
rev_96 <- transpose(rev_96)
names(rev_96) <- c("year", "gross_prod_yera", "cost_corn", "price_corn", "yield_corn")
rev_96 <- rev_96[-1, ]

rev_corn <- rbind(rev_75, rev_96)
rev_corn <- data.frame(apply(rev_corn, 2, as.numeric))
rev_corn$cost_per_acre_corn <- rev_corn$price_corn*rev_corn$yield_corn
```

```{r}
disaster <- read.csv("../data/raw/us_billion_disasters_by_year_1980-2020.csv")
disaster_col <- c("Year", "Drought.Cost", "Flooding.Cost", "Freeze.Cost", "Severe.Storm.Cost",
                  "Tropical.Cyclone.Cost", "Wildfire.Cost", "Winter.Storm.Cost")
disaster <- disaster[, disaster_col]
names(disaster)[names(disaster) %in% "Year"] <- "year"
```



```{r}
main <- merge(main, rev_corn[, c("year", "cost_per_acre_corn")], all.x = T) %>%
  merge(disaster, all.x = T) %>%
  glimpse()
main[, cost_per_acre_corn := cost_per_acre_corn*inflation_adj_ind]
```



```{r source lag function, echo=F}
create_lag <- function(data, columns, N = 4){
  datadf <- copy(data)
  
  if(!all(columns %in% names(data))){
    stop("some columns are not in the data")
  }
  
  lag_col_name = c()
  for(col in columns){
    for(lagN in 1:N){lag_col_name = append(lag_col_name, paste0(col, "_lag", lagN))}
  }
  
  lagdf <- datadf[, shift(.SD, n=1:N, fill = 0, type = "lag"), .SDcols = columns]
  colnames(lagdf) <- lag_col_name
  
  outputdf <- cbind(datadf, lagdf)
  
  return(list(data = outputdf, lag_col = lag_col_name))
}

```

```{r create lags}
base_predictors <- c("acre_planted_corn", "acre_planted_soy",  "acre_harvest_corn", "acre_harvest_soy", "yield_corn", "yield_soy", "corn_adjusted", "soy_adjusted", "pratio_cornsoy", "Drought.Cost", "Flooding.Cost", "Freeze.Cost", "Severe.Storm.Cost","Tropical.Cyclone.Cost", "Wildfire.Cost", "Winter.Storm.Cost", "cost_per_acre_corn")

lag_obj <- create_lag(data = main, columns = base_predictors, N=3)

main <- lag_obj$data[year>1979,]
lag_col <- lag_obj$lag_col
main<- as.data.table(apply(main, 2, get_impute0))
```

```{r}
PerformanceAnalytics::chart.Correlation(main[, ..base_predictors], histogram=T)
```


```{r split}
train_ind <- main$year <1988
core_col <- c("acre_planted_corn", lag_col)

# Some package uses data x combined with y as one object
train_dt <- main[train_ind, ..core_col]
test_dt <- main[!train_ind, ..core_col]

# Some packages uses data where x and y stand as different object
xtrain <- model.matrix(acre_planted_corn ~., train_dt)[, -1]
ytrain <- train_dt$acre_planted_corn

xtest <- model.matrix(acre_planted_corn ~., test_dt)[, -1]
ytest <- test_dt$acre_planted_corn
```


```{r}
set.seed(2022)
glmnet_cv <- cv.glmnet(xtrain, ytrain, alpha = 1, family = "gaussian", 
                       type.measure = "mse", nfolds = 5, nlambda = 1000)
glmnet_cv$lambda.min
plot(glmnet_cv)
coef(glmnet_cv, s = "lambda.min")

glmnet_pd_train <- predict(glmnet_cv, s = glmnet_cv$lambda.min, xtrain)
plot(ytrain, glmnet_pd_train, pch = 19, col = "brown", xlim = c(6E7, 1.2E8), ylim = c(6E7, 1.2E8))
abline(lm(glmnet_pd_train~ytrain), col = "tan")
abline(0,1, col = "gray50")
mtext(paste0("TRAIN RMSE: ",round(get_rmse(ytrain, glmnet_pd_train)/1E6, 2)))


glmnet_pd_test<- predict(glmnet_cv, s = glmnet_cv$lambda.min, xtest)
plot(ytest, glmnet_pd_test, pch = 19, col = "brown",xlim = c(6E7, 1.2E8), ylim = c(6E7, 1.2E8))
abline(lm(glmnet_pd_test~ytest), col = "tan")
abline(0,1, col = "gray50")
mtext(paste0("TEST RMSE: ",round(get_rmse(ytest, glmnet_pd_test)/1E6, 2)))


lasso_feature <- rownames(coef(glmnet_cv, s = 'lambda.min'))[coef(glmnet_cv, s = 'lambda.min')[,1]!= 0][-1]

full_fm <- paste0("acre_planted_corn ~ ", paste0(lag_col, collapse = " + "))

if(length(lasso_feature)!=0){
  lasso_fm <- paste0("acre_planted_corn ~ ", paste0(lasso_feature, collapse = " + "))
}else{
  print("All features dropped from Lasso, RF will build on full model")
  lasso_fm <- full_fm
}

```




```{r}
rf_fit <- ranger(
  formula = lasso_fm,
  data = train_dt,
  num.trees = 500,
  mtry = 3,
  min.node.size = 3,
  sample.fraction = 0.8,
  importance = 'permutation'
)
rf_pred <- predict(rf_fit, data = test_dt)
rf_rmse <- get_rmse(y = test_dt$acre_planted_corn, yhat = rf_pred$predictions)
rf_mae <- get_mae(y = test_dt$acre_planted_corn, yhat = rf_pred$predictions)

round(rf_rmse/1E6,2)
round(rf_mae/1E6,2)

plot(ytest, rf_pred$predictions, pch = 19, col = "brown",xlim = c(6E7, 1.2E8), ylim = c(6E7, 1.2E8))
abline(lm(rf_pred$predictions~ytest), col = "tan")
abline(0,1, col = "gray50")
mtext(paste0("RF TEST RMSE: ",round(get_rmse(ytest, rf_pred$predictions)/1E6, 2)))
```


# 8/18

```{r moving window fix window, warning=F, message=F}
core_col <- c("acre_planted_corn", lag_col)
# Model input
model_input <- main[, ..core_col]

x <- model.matrix(acre_planted_corn ~., model_input)[, -1]
y <- model_input$acre_planted_corn
```

```{r warning=F, message=F}
win_size <- 4:25
totalresult_glm <- list()
totalresult_rf <- list()
total_metric <- matrix(NA, ncol = 4, nrow = length(win_size))

for(window in win_size){
  
  print(window)
  totalresult_glm[[window-3]] <- matrix(NA, ncol=3, nrow = length(main$year)-window)
  totalresult_rf[[window-3]] <- matrix(NA, ncol=3, nrow = length(main$year)-window)
  
  for (i in 1:(nrow(model_input) - window - 1)){
    # Seperate X, Y for glmnet
    glmnet_cv <- cv.glmnet(x[seq(i,window - 1 + i),], y[seq(i,window - 1 + i)], alpha = 1, family = "gaussian", 
                           type.measure = "mse", nfolds = 10, nlambda = 1000)
    newx <- t(as.matrix(x[window + i,]))
    glmnet_pd <- predict(object = glmnet_cv, s = glmnet_cv$lambda.min, newx, type="response")
    observe <- y[window + i]
    totalresult_glm[[window-3]][i,1] <- main$year[window + i]
    totalresult_glm[[window-3]][i,2] <- glmnet_pd
    totalresult_glm[[window-3]][i,3] <- main$acre_planted_corn[window + i]
    
    
    rf_full <- ranger(formula = full_fm, data = model_input[seq(i,window - 1 + i),],
                      num.trees = 500,mtry = 3,min.node.size = 3,sample.fraction = 0.8,importance = 'permutation')
    rf_pd <- predict(rf_full, data = model_input[window + i, ])
    totalresult_rf[[window-3]][i,1] <- main$year[window + i]
    totalresult_rf[[window-3]][i,2] <- rf_pd$predictions
    totalresult_rf[[window-3]][i,3] <- main$acre_planted_corn[window + i]
  }
  
  total_metric[window-3, 1] <- get_rmse(na.omit(totalresult_glm[[window-3]][,2]), na.omit(totalresult_rf[[window-3]][,3]))/1E6
  total_metric[window-3, 2]<- get_mae(na.omit(totalresult_glm[[window-3]][,2]), na.omit(totalresult_rf[[window-3]][,3]))/1E6
  total_metric[window-3, 3]<- get_rmse(na.omit(totalresult_rf[[window-3]][,2]), na.omit(totalresult_rf[[window-3]][,3]))/1E6
  total_metric[window-3, 4]<- get_mae(na.omit(totalresult_rf[[window-3]][,2]), na.omit(totalresult_rf[[window-3]][,3]))/1E6
  
}; beepr::beep(2)


total_metric <- as.data.frame(total_metric)
names(total_metric)<- c("rmse_glm", "mae_glm","rmse_rf","mae_rf")
total_metric$win_size <- win_size

ggplot(total_metric) +
  geom_vline(xintercept = win_size, color = "gray85") +
  geom_hline(yintercept = seq(3,6,.5), color = "gray85") +
  theme_classic() +
  geom_line(aes(x = win_size, y = mae_glm, color = "mae_glm")) +
  geom_line(aes(x = win_size, y = mae_rf, color = "mae_rf"))
```


```{r}
# round(get_mae(totalresult$glm_mw_pd, totalresult$observe)/1E6,2)
# round(get_mae(totalresult$rf_mw_pd, totalresult$observe)/1E6,2)
# 
# round(get_rmse(totalresult$glm_mw_pd, totalresult$observe)/1E6,2)
# round(get_rmse(totalresult$rf_mw_pd, totalresult$observe)/1E6,2)
# 
# ggplot(totalresult) +
#   geom_line(aes(x = year, y = glm_mw_pd, color = "glm predicted") ) +
#   geom_line(aes(x = year, y = rf_mw_pd, color = "rf predicted")) +
#   geom_line(aes(x = year, y = observe, color = "observed")) +
#   geom_vline(xintercept = 2000:2018, color = "gray80") +
#   theme_classic()
```
